[build]
  command = "npm run build"
  publish = "dist/portfolio-katy/browser"
  functions = ".netlify/functions"

[[plugins]]
  package = "@netlify/angular-runtime"

[[redirects]]
  from = "/*"
  to = "/.netlify/edge-functions/angular-ssr"
  status = 200
